server:
  context-path: /jas-activiti

begonia:
  starter:
    suffix:  good  morning
    contextPath: ${server.context-path}
spring:
  application:
    name: jas-activiti-web

  # 当前maven打包的profile
  profiles:
    active: @profileActive@

  # UTF-8编码
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

hello: Hello spring-boot-assembly



